export const GET_CATEGORIES = 'GET_CATEGORIES'
export const GET_POSTS = 'GET_POSTS'
export const INCREMENT_VOTE_SCORE = 'INCREMENT_VOTE_SCORE'
export const DECREMENT_VOTE_SCORE = 'DECREMENT_VOTE_SCORE'
