export const GET_POSTS = "GET_POSTS";
export const INCREMENT_VOTE_SCORE = "INCREMENT_VOTE_SCORE";
export const DECREMENT_VOTE_SCORE = "DECREMENT_VOTE_SCORE";
export const DELETE_POST = "DELETE_POST";
export const GET_CATEGORIES = "GET_CATEGORIES";
export const POST_ADD = "POST_ADD";
export const CLOSE_SNACKBAR = "CLOSE_SNACKBAR";
export const GET_DETAILS_POST = "GET_DETAILS_POST";
export const GET_DETAILS_COMMENTS_POST = "GET_DETAILS_COMMENTS_POST";
export const POST_ADD_COMMENTS = "POST_ADD_COMMENTS";
export const INCREMENT_VOTE_SCORE_COMMENTS = "INCREMENT_VOTE_SCORE_COMMENTS";
export const DECREMENT_VOTE_SCORE_COMMENTS = "DECREMENT_VOTE_SCORE_COMMENTS";
export const CLEAN_DETAILS_POST = "CLEAN_DETAILS_POST";
export const DELETE_COMMENTS = "DELETE_COMMENTS";
export const CLOSE_SNACKBAR_DELETE_COMMENTS = "CLOSE_SNACKBAR_DELETE_COMMENTS"
export const CLOSE_SNACKBAR_ADD_COMMENTS = "CLOSE_SNACKBAR_ADD_COMMENTS"

export const CLOSE_SNACKBAR_DELETE_POST = "CLOSE_SNACKBAR_DELETE_POST"

// export const GET_POSTS_CATEGORY_REACT = "GET_POSTS_CATEGORY_REACT";
// export const GET_POSTS_CATEGORY_REDUX = "GET_POSTS_CATEGORY_REDUX";
// export const GET_POSTS_CATEGORY_UDACITY = "GET_POSTS_CATEGORY_UDACITY";
