export const GET_POSTS = "GET_POSTS";
export const INCREMENT_VOTE_SCORE = "INCREMENT_VOTE_SCORE";
export const DECREMENT_VOTE_SCORE = "DECREMENT_VOTE_SCORE";
export const GET_CATEGORIES = "GET_CATEGORIES";
export const POST_ADD = "POST_ADD";
export const PUT_EDIT_POST = "PUT_EDIT_POST";
export const CLOSE_SNACKBAR_EDIT_POST = "CLOSE_SNACKBAR_EDIT_POST"
export const DELETE_POST = "DELETE_POST";
export const CLOSE_SNACKBAR = "CLOSE_SNACKBAR";
export const GET_DETAILS_POST = "GET_DETAILS_POST";
export const GET_DETAILS_COMMENTS_POST = "GET_DETAILS_COMMENTS_POST";
export const INCREMENT_VOTE_SCORE_COMMENTS = "INCREMENT_VOTE_SCORE_COMMENTS";
export const DECREMENT_VOTE_SCORE_COMMENTS = "DECREMENT_VOTE_SCORE_COMMENTS";
export const DELETE_COMMENTS = "DELETE_COMMENTS";
export const CLOSE_SNACKBAR_DELETE_COMMENTS = "CLOSE_SNACKBAR_DELETE_COMMENTS"
export const POST_ADD_COMMENTS = "POST_ADD_COMMENTS";
export const CLOSE_SNACKBAR_ADD_COMMENTS = "CLOSE_SNACKBAR_ADD_COMMENTS"
export const PUT_EDIT_COMMENT = "PUT_EDIT_COMMENT"
export const CLOSE_SNACKBAR_EDIT_COMMENT = "CLOSE_SNACKBAR_EDIT_COMMENT"
export const GET_DETAILS_COMMENT = "GET_DETAILS_COMMENT"



